-- 应用启动时自动执行的幂等建表脚本（H2 本地库与 PostgreSQL 均兼容）
CREATE TABLE IF NOT EXISTS game_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  session_date DATE NOT NULL,
  time_slot VARCHAR(20) NOT NULL,
  seat_count INT NOT NULL CHECK (seat_count > 0),
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN', -- OPEN=上架中可报名, OFF=已下架
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS session_signups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES game_sessions (id) ON DELETE CASCADE,
  player_name VARCHAR(80) NOT NULL,
  status VARCHAR(20) NOT NULL, -- CONFIRMED=已占位, WAITLIST=候补中, CANCELLED=已取消
  seq BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_signup_session_player UNIQUE (session_id, player_name)
);

CREATE INDEX IF NOT EXISTS idx_sessions_date ON game_sessions (session_date);
CREATE INDEX IF NOT EXISTS idx_signups_session_status ON session_signups (session_id, status, seq);
